apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: galin10/api:1.0.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: chatapp-config
            - secretRef:
                name: chatapp-secrets
