apiVersion: v1
kind: ConfigMap
metadata:
  name: chatapp-config
data:
  POSTGRES_USER: 'postgres'
  POSTGRES_DB: 'chatapp'
  POSTGRES_URL: 'postgresql://postgres:password@postgres:5432/chatapp?schema=public'
  MONGO_URI: 'mongodb://mongo:password@mongo:27017'
  API_PORT: '5000'
