services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp
    ports:
      - '5432:5432'
    volumes:
      - chatapp_data:/var/lib/postgresql/data

  # TODO Create other services such as web, api, prisma studio?, AI service for content detection?

volumes:
  chatapp_data:
